springs:
  profiles:
    active: dev

---
springs:
  config:
    activate:
      on-profile: dev

server:
  port: 8080
app:
  env: dev

---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8081
app:
  env: test