springs:
  profiles:
    active: dev

---
springs:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:planova
    driverClassName: org.h2.Driver
    username: root
    password: "root"

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



server:
  port: 8080
app:
  env: dev

---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8081
app:
  env: test